language: java
jdk:
  - oraclejdk8
sudo: true
before_install:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
install:
  - ./shared/dev-tasks/install-dependencies.sh
script:
  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "false" ] && ./gradlew test || ./gradlew jshint'
